# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(159, 159, 159)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:rgb(17, 17, 17); font-size:50pt")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 384))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 1)
        self.DOD_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.DOD_path_label.setAutoFillBackground(False)
        self.DOD_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.DOD_path_label.setObjectName("DOD_path_label")
        self.gridLayout.addWidget(self.DOD_path_label, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 3, 1, 1)
        self.DOD_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.DOD_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.DOD_set_dir_button.setObjectName("DOD_set_dir_button")
        self.gridLayout.addWidget(self.DOD_set_dir_button, 3, 4, 1, 1)
        self.HL2DM_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.HL2DM_path_label.setAutoFillBackground(False)
        self.HL2DM_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.HL2DM_path_label.setObjectName("HL2DM_path_label")
        self.gridLayout.addWidget(self.HL2DM_path_label, 2, 2, 1, 1)
        self.HLDMS_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.HLDMS_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.HLDMS_set_dir_button.setObjectName("HLDMS_set_dir_button")
        self.gridLayout.addWidget(self.HLDMS_set_dir_button, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_7.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.L4D2_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.L4D2_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.L4D2_set_dir_button.setObjectName("L4D2_set_dir_button")
        self.gridLayout.addWidget(self.L4D2_set_dir_button, 4, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 3, 1, 1)
        self.L4D2_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.L4D2_path_label.setAutoFillBackground(False)
        self.L4D2_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.L4D2_path_label.setObjectName("L4D2_path_label")
        self.gridLayout.addWidget(self.L4D2_path_label, 4, 2, 1, 1)
        self.TF2_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TF2_path_label.sizePolicy().hasHeightForWidth())
        self.TF2_path_label.setSizePolicy(sizePolicy)
        self.TF2_path_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TF2_path_label.setAutoFillBackground(False)
        self.TF2_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.TF2_path_label.setScaledContents(False)
        self.TF2_path_label.setWordWrap(False)
        self.TF2_path_label.setObjectName("TF2_path_label")
        self.gridLayout.addWidget(self.TF2_path_label, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.HLDMS_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.HLDMS_path_label.setAutoFillBackground(False)
        self.HLDMS_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.HLDMS_path_label.setObjectName("HLDMS_path_label")
        self.gridLayout.addWidget(self.HLDMS_path_label, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.HL2DM_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.HL2DM_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.HL2DM_set_dir_button.setObjectName("HL2DM_set_dir_button")
        self.gridLayout.addWidget(self.HL2DM_set_dir_button, 2, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        self.TF2_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.TF2_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.TF2_set_dir_button.setObjectName("TF2_set_dir_button")
        self.gridLayout.addWidget(self.TF2_set_dir_button, 0, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem11, 5, 1, 1, 1)
        self.CSS_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.CSS_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.CSS_set_dir_button.setObjectName("CSS_set_dir_button")
        self.gridLayout.addWidget(self.CSS_set_dir_button, 5, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem12, 5, 3, 1, 1)
        self.CSGO_set_dir_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.CSGO_set_dir_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(202, 202, 202);\n"
"border-style: inset;\n"
"}")
        self.CSGO_set_dir_button.setObjectName("CSGO_set_dir_button")
        self.gridLayout.addWidget(self.CSGO_set_dir_button, 6, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem13, 6, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem14, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet("font: 22pt \"Roboto\";\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.CSGO_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.CSGO_path_label.setAutoFillBackground(False)
        self.CSGO_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.CSGO_path_label.setObjectName("CSGO_path_label")
        self.gridLayout.addWidget(self.CSGO_path_label, 6, 2, 1, 1)
        self.CSS_path_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.CSS_path_label.setAutoFillBackground(False)
        self.CSS_path_label.setStyleSheet("font: 16pt \"Roboto\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.CSS_path_label.setObjectName("CSS_path_label")
        self.gridLayout.addWidget(self.CSS_path_label, 5, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        spacerItem15 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_4.addItem(spacerItem15)
        self.download_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_button.sizePolicy().hasHeightForWidth())
        self.download_button.setSizePolicy(sizePolicy)
        self.download_button.setStyleSheet("QPushButton {\n"
"font: 16pt \"Roboto\";\n"
"background-color: rgb(101, 234, 29);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(92, 208, 25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(86, 194, 23);\n"
"}")
        self.download_button.setObjectName("download_button")
        self.verticalLayout_4.addWidget(self.download_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SOURCE: CROSSROADS"))
        self.label_5.setText(_translate("MainWindow", "DOD"))
        self.DOD_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.DOD_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.HL2DM_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.HLDMS_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.label_7.setText(_translate("MainWindow", "L4D2"))
        self.label_4.setText(_translate("MainWindow", "HL2:DM"))
        self.L4D2_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.L4D2_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.TF2_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.HLDMS_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.label_2.setText(_translate("MainWindow", "TF2"))
        self.label_3.setText(_translate("MainWindow", "HLDM:S"))
        self.HL2DM_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.TF2_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.label_8.setText(_translate("MainWindow", "CS:S"))
        self.CSS_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.CSGO_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.label_9.setText(_translate("MainWindow", "CS:GO"))
        self.CSGO_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.CSS_path_label.setText(_translate("MainWindow", "PATH NOT FOUND"))
        self.download_button.setText(_translate("MainWindow", "Download FASTDL Content"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
