# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 700))
        MainWindow.setStyleSheet("background-color: black")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1078, 570))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.TF2_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TF2_path_label.sizePolicy().hasHeightForWidth())
        self.TF2_path_label.setSizePolicy(sizePolicy)
        self.TF2_path_label.setAutoFillBackground(False)
        self.TF2_path_label.setStyleSheet("color: #fff;\n"
"background-color: #000;")
        self.TF2_path_label.setScaledContents(False)
        self.TF2_path_label.setWordWrap(False)
        self.TF2_path_label.setObjectName("TF2_path_label")
        self.gridLayout.addWidget(self.TF2_path_label, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.TF2_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.TF2_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.TF2_set_dir_button.setObjectName("TF2_set_dir_button")
        self.gridLayout.addWidget(self.TF2_set_dir_button, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.HLDMS_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HLDMS_path_label.sizePolicy().hasHeightForWidth())
        self.HLDMS_path_label.setSizePolicy(sizePolicy)
        self.HLDMS_path_label.setAutoFillBackground(False)
        self.HLDMS_path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: black;")
        self.HLDMS_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.HLDMS_path_label.setObjectName("HLDMS_path_label")
        self.gridLayout.addWidget(self.HLDMS_path_label, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 1, 1, 1)
        self.L4D2_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.L4D2_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.L4D2_set_dir_button.setObjectName("L4D2_set_dir_button")
        self.gridLayout.addWidget(self.L4D2_set_dir_button, 4, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 3, 1, 1)
        self.HLDMS_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HLDMS_set_dir_button.sizePolicy().hasHeightForWidth())
        self.HLDMS_set_dir_button.setSizePolicy(sizePolicy)
        self.HLDMS_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.HLDMS_set_dir_button.setObjectName("HLDMS_set_dir_button")
        self.gridLayout.addWidget(self.HLDMS_set_dir_button, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.HL2DM_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.HL2DM_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.HL2DM_set_dir_button.setObjectName("HL2DM_set_dir_button")
        self.gridLayout.addWidget(self.HL2DM_set_dir_button, 2, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 3, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 3, 3, 1, 1)
        self.DOD_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.DOD_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.DOD_set_dir_button.setObjectName("DOD_set_dir_button")
        self.gridLayout.addWidget(self.DOD_set_dir_button, 3, 4, 1, 1)
        self.HL2DM_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HL2DM_path_label.sizePolicy().hasHeightForWidth())
        self.HL2DM_path_label.setSizePolicy(sizePolicy)
        self.HL2DM_path_label.setAutoFillBackground(False)
        self.HL2DM_path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: black;")
        self.HL2DM_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.HL2DM_path_label.setObjectName("HL2DM_path_label")
        self.gridLayout.addWidget(self.HL2DM_path_label, 2, 2, 1, 1)
        self.DOD_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DOD_path_label.sizePolicy().hasHeightForWidth())
        self.DOD_path_label.setSizePolicy(sizePolicy)
        self.DOD_path_label.setAutoFillBackground(False)
        self.DOD_path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: black;")
        self.DOD_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DOD_path_label.setObjectName("DOD_path_label")
        self.gridLayout.addWidget(self.DOD_path_label, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.L4D2_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L4D2_path_label.sizePolicy().hasHeightForWidth())
        self.L4D2_path_label.setSizePolicy(sizePolicy)
        self.L4D2_path_label.setAutoFillBackground(False)
        self.L4D2_path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: black;")
        self.L4D2_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.L4D2_path_label.setObjectName("L4D2_path_label")
        self.gridLayout.addWidget(self.L4D2_path_label, 4, 2, 1, 1)
        self.CSS_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.CSS_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.CSS_set_dir_button.setObjectName("CSS_set_dir_button")
        self.gridLayout.addWidget(self.CSS_set_dir_button, 5, 4, 1, 1)
        self.CSGO_set_dir_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.CSGO_set_dir_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #fff;\n"
"  background-color: #000;\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.CSGO_set_dir_button.setObjectName("CSGO_set_dir_button")
        self.gridLayout.addWidget(self.CSGO_set_dir_button, 6, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 6, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 5, 1, 1, 1)
        self.CSS_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CSS_path_label.sizePolicy().hasHeightForWidth())
        self.CSS_path_label.setSizePolicy(sizePolicy)
        self.CSS_path_label.setAutoFillBackground(False)
        self.CSS_path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: black;")
        self.CSS_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CSS_path_label.setObjectName("CSS_path_label")
        self.gridLayout.addWidget(self.CSS_path_label, 5, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 5, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.CSGO_path_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CSGO_path_label.sizePolicy().hasHeightForWidth())
        self.CSGO_path_label.setSizePolicy(sizePolicy)
        self.CSGO_path_label.setAutoFillBackground(False)
        self.CSGO_path_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: black;")
        self.CSGO_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CSGO_path_label.setObjectName("CSGO_path_label")
        self.gridLayout.addWidget(self.CSGO_path_label, 6, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 6, 3, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_button.sizePolicy().hasHeightForWidth())
        self.download_button.setSizePolicy(sizePolicy)
        self.download_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.download_button.setStyleSheet("QPushButton {\n"
"  font-family: \'VCR OSD Mono\', monospace;\n"
"  font-size: 20px;\n"
"  font-weight: bold;\n"
"  padding: 8px;\n"
"  text-transform: uppercase;\n"
"  text-decoration: none;\n"
"  color: #000;\n"
"  background-color: rgb(101, 234, 29);\n"
"  border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(93, 209, 25);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(81, 177, 20);\n"
"    border-style: inset;\n"
"    margin-left: 1px;\n"
"    margin-top: 1px;\n"
"}")
        self.download_button.setObjectName("download_button")
        self.verticalLayout_4.addWidget(self.download_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Source: Crossroads FastDL Manager"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Team Fortress 2</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/TF2_Icon.png\"/></p></body></html>"))
        self.TF2_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Half-Life Deathmatch: Source</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/HLDMS_icon.png\"/></p></body></html>"))
        self.TF2_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.label_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Counter-Strike: Source</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/CSS_icon.png\"/></p></body></html>"))
        self.label_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Day of Defeat: Source</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/DODS_icon.png\"/></p></body></html>"))
        self.HLDMS_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.L4D2_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.HLDMS_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Half-Life 2: Deathmatch</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/HL2DM_icon.png\"/></p></body></html>"))
        self.HL2DM_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.DOD_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.HL2DM_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.DOD_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.label_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Left 4 Dead 2</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/L4D2_icon.png\"/></p></body></html>"))
        self.L4D2_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.CSS_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.CSGO_set_dir_button.setText(_translate("MainWindow", "Locate Game Directory"))
        self.CSS_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.label_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>Counter-Strike: Global Offensive</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/CSGO_icon.png\"/></p></body></html>"))
        self.CSGO_path_label.setText(_translate("MainWindow", "CHOOSE \"STEAMAPPS/COMMON\" GAME FOLDER"))
        self.download_button.setText(_translate("MainWindow", "Download FASTDL Content"))